"""add group_messages and student_reports tables

Revision ID: 00fa41353828
Revises: 6f3b2a1d9c44
Create Date: 2026-03-10 06:18:55.747717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fa41353828'
down_revision: Union[str, Sequence[str], None] = '6f3b2a1d9c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Apenas criar as novas tabelas (group_messages e student_reports)
    # Ignorar alterações em colunas existentes (problemas com SQLite)
    
    op.create_table('student_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_reports_student_id'), 'student_reports', ['student_id'], unique=False)
    
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_id'), 'group_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_messages_id'), table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_student_reports_student_id'), table_name='student_reports')
    op.drop_table('student_reports')
    # ### end Alembic commands ###
    op.create_index(op.f('ix_classroom_members_classroom_id'), 'classroom_members', ['classroom_id'], unique=False)
    op.alter_column('classroom_members', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('classroom_members', 'role',
               existing_type=sa.Enum('admin', 'moderator', 'teacher', 'student', name='classroommemberrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
    op.drop_index(op.f('ix_group_messages_id'), table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_student_reports_student_id'), table_name='student_reports')
    op.drop_table('student_reports')
    # ### end Alembic commands ###
